// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptfbwxkhmttdmbtjgkbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZmJ3eGtobXR0ZG1idGpna2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyNjg2ODMsImV4cCI6MjA4MTg0NDY4M30.asfoO4bdqDQooJ544uPmMD2k7EXOu5t4gEyksWYFg-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});